# Generated by Django 4.2.7 on 2023-12-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_img_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='startPage',
            field=models.TextField(null=True),
        ),
    ]
