# Generated by Django 4.2.7 on 2024-08-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_startpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='typeOfAction',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='typeOfPlatform',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
